eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 8762
spring:
  application:
    name: zuul-service

zuul:
  routes:
    catalog:
      path: /catalog/*
      stripPrefix: false
    order:
      path: /**/order
      stripPrefix: false
management:
  endpoints:
    web:
      exposure:
        include: info, health, routes, filters
  endpoint:
    routes:
      enabled: true
    filters:
      enabled: true

